onlyBuiltDependencies:
  - esbuild
trustPolicy: no-downgrade
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@vpmedia/bitcharify'
  - '@vpmedia/bitcharify-phaser2'
  - '@vpmedia/bitcharify-phaser3'
  - '@vpmedia/phaser'
